<?

return array(
	//'redirect' => '/company',

	'title' => array(
		'page' => 'Отпевание: Суть и традиции ритуала',
		'menu' => 'Отпевание',
		'content' => 'Проведение отпевания: Духовное прощание с усопшим',
	),

	'block-menu' => array(
		'pic' => 'posts/2/3.webp',
		'pic' => 'posts/2/1.webp',
		//'bg-pos' => 'auto 61%',
		'bg-size' => 'cover',
		'size' => 2,
		//'hover' => 2,
	),

	'content' => array(
		'content-tpl' => array('posts', 'data/content/orthodox'),
	),

);