<?
/*
	https://coolors.co/fafafa
	https://yandex.ru/yandsearch?text=цвет яндекса&lr=2
	https://colorscheme.ru/color-names.html
	https://coolors.co/5A616F-606674
*/

$cssColorNames = array(
	'white' => '#ffffff',
	'seasalt' => '#fafafa',
	'flash-white' => '#efefef', //slightly-grey
	'fire-red' => '#d62829',
	'blue-grey' => '#5A6472',
	'blue-azure' => '#3081E1',
	//alink
	'tekhelet' => '#551a8b', //Техелет — "сине-фиолетовый"
	//visited-alink
);


//step: добавляем проименованные название
$cssColors = array(
	//'c1' => '#1e274d',
);

return $cssColorNames + $cssColors;