<?

return array(
	//const MQ6 => 1980,
	//const MQ1D => 1920,
	'max' => 1832, //$MQX,
	'plan' => 1800, //$MQX,
	//const MQ1E => 1600,
	//const MQ1C => 1366,
	//const MQ1B => 1280,
	//'MQ1' => 1214, //MQ1
	//'1' => 1214, //MQ1
	'1' => 1214, //MQ1
	'base' => '1',
	//'header' => 1214,
	'header' => '1',
	//static $_MQ1,
	//static $MQ_S,
	//static $_MQ_S,
	'2++' => 960, // 2-- / 2++ / 26
	'2+' => 877, //MQ2C / 2-2 / 2+ / 2- / 23
	'2' => 810, //MQ2
	'3+' => 667, //MQ3B
	'3' => 480, //MQ3
	//const MQ4 => 414,
	//const MQ0B => 360,
	//const MQ0 => 300,
	'min' => 360,
	//static $_MQ0,
	//static $MQZ,
);