<?

return $cssSite = array(

	'w-side' => 211,

	//для lay-app
	'app-ph' => 25, # —
	'app-pv' => 15, # |

	//для lay-section
	'section-ps' => 20, //размер отступов внутри секций / расстояние между секциями
	'section-p' => 'section-ps', //'section-pv' => 'section-p', 'section-ph' => 'section-p',
	'section-cell-sep' => 'section-ps',
	'section-row-sep' => 'app-pv',

	'main-bg' => '#ededee',
	'section-bg' => '#f8f8fa', //white
	'section-bc' => '#f6f6f6',
	'section-br' => 18,

	'b-button-bg' => '#3a3a3a',
	'b-button-bc' => '#131313',

	's-button-bg' => 'white',
	's-button-bc' => '#2050d6',

	//'bu-button-bg' => '#3553fd',
	//'bu-button-bc' => '#2141fe',
	'bu-button-bg' => '#2050d6',
	'bu-button-bc' => '#0033cd',


	'side-bg' => 'white',
	'menu-sub-border' => 'warn-border',
	'r-button-bg' => 'warn-border',
	'content-bg' => 'white',
	'black-text' => 'rgba(0, 0, 0, 0.87)',
	'spinner' => '#c8c8c8', //Silver
	'spinner-bg' => '#f2f2f2', //White smoke
	'section-head-hover' => '#f5f5f5', //White smoke 2
	//closed-section head-hover
	'field-border' => 'rgba(0, 0, 0, 0.4)', //White smoke 2
	'table-border' => 'rgba(64, 77, 92, 0.25)',
	'table-th' => 'rgb(239, 239, 239)',
	'warn-border' => 'fire-red',

	//'основной-текст' => 'dark-black',

);