_vue('dashboard', function(_log){

    return {
        data(){
            //_log('data');
            return {
                content: '- L o g i n'
            }
        },

        methods: {

        },

        mounted(){ _
            //log('mounted');
        },
        created(){
            //_log('created');
        },
        beforeMount(){
            //_log('beforeMount');
        },
    }
})