<?

return array(
	//'redirect' => '/company',

	'title' => array(
		'page' => 'Ритуальный агент',
		'menu' => 'Ритуальный агент',
		'content' => 'Как ритуальный агент помогает в организации прощания',
		//'content' => 'Ритуальный агент: ваш помощник в трудные времена',
	),

	'block-menu' => array(
		//'pic' => 'posts/1/2.webp',
		//'bg-pos' => '80%',

		'pic' => 'posts/4/1.webp',
				//'pic' => 'posts/1/4.webp',
				//'pic' => 'posts/1/8.webp',
			//'pic' => 'posts/1/9.webp',
		'bg-pos' => '50%',

		'size' => 1,
		//'hover' => 2,
	),

	'content' => array(
		'content-tpl' => array('posts', 'data/content/agent'),
	),

);