<?

return array(
	//'redirect' => '/company',

	'title' => array(
		'page' => 'Организация похорон',
		'menu' => 'Похороны',
		'content' => 'Организация прощания: от планирования до поминок',
		//'content' => 'Шаги и советы по организации достойных похорон',
	),

	'block-menu' => array(
		//'pic' => 'posts/1/2.webp',
		//'bg-pos' => '80%',

		'pic' => 'posts/3/4.webp',
				//'pic' => 'posts/1/4.webp',
				//'pic' => 'posts/1/8.webp',
			//'pic' => 'posts/1/9.webp',
		'bg-pos' => '50%',

		'size' => 2,
		//'hover' => 2,
	),

	'content' => array(
		'content-tpl' => array('posts', 'data/content/burial'),
	),

);