<?

return array(
	//'redirect' => '/company',

	'title' => array(
		'page' => 'Транспортировка',
		'menu' => 'Транспортировка',
		//'top-menu' => 'Транспортировка',
		'block-menu' => 'Перевозка тела',
		'content' => 'Перевозка тела в морг',
	),

	'block-menu' => array(
		//'pic' => 'posts/1/2.webp',
		//'bg-pos' => '80%',

		'pic' => 'posts/1/3.webp',
				//'pic' => 'posts/1/4.webp',
				//'pic' => 'posts/1/8.webp',
			//'pic' => 'posts/1/9.webp',
		'bg-pos' => '50%',

		'size' => 1,
		//'hover' => 2,
	),

	'content' => array(
		'content-tpl' => array('posts', 'data/content/transport'),
	),

);