<?

return array(
	//'redirect' => '/company',

	'title' => array(
		//'page' => '',
		'menu' => 'Партнёр',
		'menu-html' => join('<br />', array(
			'Партнёр',
			'granitplace.ru',
		)),
	),
	'link' => array(
		'external' => 'https://granitplace.ru'
	),
	'footer-menu' => array(
		'pic' => 'icon/graniplace/android-icon-96x96.png',
		'h' => 65,
		//'pic' => 'icon/graniplace/logo-header.w_03.png',
	),

	'content' => array(
		'content-tpl' => 'uc',
	),

);